<a href="https://colab.research.google.com/github/DanielKorenDataScience/ClassificationProject/blob/main/Classification_Project_Shufersal_Cans.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Classification Project - CANS

for Shufersal on-line orders, for replacing of missing products, will predict the replacement success!

In [9]:
import requests
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

from IPython.display import display
p = print
d = display

# Get Data

## Raw Data

To run the raw section, one must load Sweets_ver2.csv to local google drive and change the next line to True

In [10]:
id = ''  # name of result file
prefix = 'Shufersal_cans'

RAW = True
DIFF = False

if not DIFF:
  id = 'no_diff'

In [11]:
fname = 'Cans.csv'
subdir = ''
data_url = 'https://raw.githubusercontent.com/DanielKorenDataScience/ClassificationProject/main/' + subdir + fname

df1 = pd.read_csv(data_url, nrows=1)
df2 = pd.read_csv(data_url, usecols=[i for i in range(82) if not i in[0,8,10,12,14,16,18,20,24,26,27,48,50,52,54,56,58,62,64,65]])
d(df1)

,OrderNumbert,HouseHoldID,LocationCityName,QuarterNumber,MonthNumber,WeekNumber,DayNumberInWeek,PeriodHoliday,TransactionDate,DepartmentCode,DepartmentName,CategoryCode,CategoryName,GroupCode,GroupName,SubGroupCode,SubGroupName,CompoundID,CompoundIDDesc,ParentProductNumber,ProductDescription,BrandIndDesc,BrandName,VendorNumber,VendorName,UnitOfMeasure,ItemsPerPackageWH,DescriptionTavit,Price,Quantity,cntPrdAll,NetSaleAmountAll,NetSaleNoVatPrdLast3Months,QuantSale,cntMonths,DiscountPerUnit,isPromo,Energy,Pachmema,Natran,Helbon,Shuman,ShumanRavuy,ShumanTrans,Colastrol,SivimTzunatim,CafiotSucar,DepartmentCodeSubs,DepartmentNameSusb,CategoryCodeSubs,CategoryNameSubs,GroupCodeSubs,GroupNameSubs,SubGroupCodeSubs,SubGroupNameSubs,CompoundIDSubs,CompoundIDDescSubs,ProductNumberSubs,ProductDescriptionSubs,BrandIndDescSuss,BrandNameSubs,VendorNumberSubs,VendorNameSubs,UnitOfMeasureSubs,ItemsPerPackageWHSubs,DescriptionTavitSubs,PriceSubs,NetSaleNoVatPrdSubs,QuantSaleSubs,cntMonthsSubs,DiscountPerUnitSubs,EnergySubs,PachmemaSubs,NatranSubs,HelbonSubs,ShumanSubs,ShumanRavuySubs,ShumanTransSubs,ColastrolSubs,SivimTzunatimSubs,CafiotSucarSusb,CorrelateItemStatusCode
0,5499,1,תל אביב,202101,202103,202110,4,NotHoliday,10/03/2021,10,10-מזון יבש,1,שימורים,640,מוצרי עגבניות,4,עגבניות מרוסקות,-8005110170300,עגבניות חתוכות דק 3*400ג,8005110170300,עגבניות חתוכות דק 3*400ג,MUTTI,לא מותג פרטי,913847,"רסטרטו יבוא ושיווק בע""מ",1.2,8,3 * 400 גרם,10,2,46,879.75,1148095.31,0.2,16,6.89,PromoSusbDiffPromo,26,3.9,120,1.2,0.2,NaN,NaN,NaN,NaN,NaN,10,10-מזון יבש,1,שימורים,640,מוצרי עגבניות,4,עגבניות מרוסקות,-7296073414278,עגבניות חתוכות דק 3*400ג,7296073414278,עגבניות חתוכות דק 3*400ג,שופרסל,מותג פרטי,921174,הדס 1987 בעמ P.L פרי ניר,1.2,8,3 * 400 גרם,10,118719.7,0.6,9,NaN,26,4.2,114,1.6,NaN,NaN,NaN,NaN,1.5,0.75,1

In [12]:
def get_raw(fname, subdir=''):
  data_url = 'https://raw.githubusercontent.com/DanielKorenDataScience/ClassificationProject/main/' + subdir + fname
  return pd.read_csv(data_url)

In [13]:
def diff_list(li1, li2):
  p(len(li1), len(li2))
  return [i for i in li1 + li2 if i not in li1 or i not in li2]

### Cans dataset identical features as Sweets - the diff list returns empty list

In [14]:
if RAW:
  fname = 'Sweets.csv'
  df_sweet = get_raw(fname)
  d(diff_list(list(df1.columns), list(df_sweet.columns)))

82 82

[]

In [15]:
if RAW:
  df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1 entries, 0 to 0
Data columns (total 82 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   OrderNumbert                1 non-null      int64
 1   HouseHoldID                 1 non-null      int64
 2   LocationCityName            1 non-null      object
 3   QuarterNumber               1 non-null      int64
 4   MonthNumber                 1 non-null      int64
 5   WeekNumber                  1 non-null      int64
 6   DayNumberInWeek             1 non-null      int64
 7   PeriodHoliday               1 non-null      object
 8   TransactionDate             1 non-null      object
 9   DepartmentCode              1 non-null      int64
 10  DepartmentName              1 non-null      object
 11  CategoryCode                1 non-null      int64
 12  CategoryName                1 non-null      object
 13  GroupCode                   1 non-null      int64
 14  GroupName                   1 non-null      object
 15  SubGroupCode                1 non-null      int64
 16  SubGroupName                1 non-null      object
 17  CompoundID                  1 non-null      int64
 18  CompoundIDDesc              1 non-null      object
 19  ParentProductNumber         1 non-null      int64
 20  ProductDescription          1 non-null      object
 21  BrandIndDesc                1 non-null      object
 22  BrandName                   1 non-null      object
 23  VendorNumber                1 non-null      int64
 24  VendorName                  1 non-null      object
 25  UnitOfMeasure               1 non-null      float64
 26  ItemsPerPackageWH           1 non-null      int64
 27  DescriptionTavit            1 non-null      object
 28  Price                       1 non-null      int64
 29  Quantity                    1 non-null      int64
 30  cntPrdAll                   1 non-null      int64
 31  NetSaleAmountAll            1 non-null      float64
 32  NetSaleNoVatPrdLast3Months  1 non-null      float64
 33  QuantSale                   1 non-null      float64
 34  cntMonths                   1 non-null      int64
 35  DiscountPerUnit             1 non-null      float64
 36  isPromo                     1 non-null      object
 37  Energy                      1 non-null      int64
 38  Pachmema                    1 non-null      float64
 39  Natran                      1 non-null      int64
 40  Helbon                      1 non-null      float64
 41  Shuman                      1 non-null      float64
 42  ShumanRavuy                 0 non-null      float64
 43  ShumanTrans                 0 non-null      float64
 44  Colastrol                   0 non-null      float64
 45  SivimTzunatim               0 non-null      float64
 46  CafiotSucar                 0 non-null      float64
 47  DepartmentCodeSubs          1 non-null      int64
 48  DepartmentNameSusb          1 non-null      object
 49  CategoryCodeSubs            1 non-null      int64
 50  CategoryNameSubs            1 non-null      object
 51  GroupCodeSubs               1 non-null      int64
 52  GroupNameSubs               1 non-null      object
 53  SubGroupCodeSubs            1 non-null      int64
 54  SubGroupNameSubs            1 non-null      object
 55  CompoundIDSubs              1 non-null      int64
 56  CompoundIDDescSubs          1 non-null      object
 57  ProductNumberSubs           1 non-null      int64
 58  ProductDescriptionSubs      1 non-null      object
 59  BrandIndDescSuss            1 non-null      object
 60  BrandNameSubs               1 non-null      object
 61  VendorNumberSubs            1 non-null      int64
 62  VendorNameSubs              1 non-null      object
 63  UnitOfMeasureSubs           1 non-null      float64
 64  ItemsPerPackageWHSubs       1 non-null      int64
 65  DescriptionTavitSubs        1 non-null      object
 66  PriceSubs                   1 non-null      int64
 67  NetSaleNoVatPrdSubs         1 non-null      float64
 68  QuantSaleSubs               1 non-null      float64
 69  cntMonthsSubs               1 non-null      int64
 70  DiscountPerUnitSubs         0 non-null      float64
 71  EnergySubs                  1 non-null      int64
 72  PachmemaSubs                1 non-null      float64
 73  NatranSubs                  1 non-null      int64
 74  HelbonSubs                  1 non-null      float64
 75  ShumanSubs                  0 non-null      float64
 76  ShumanRavuySubs             0 non-null      float64
 77  ShumanTransSubs             0 non-null      float64
 78  ColastrolSubs               0 non-null      float64
 79  SivimTzunatimSubs           1 non-null      float64
 80  CafiotSucarSusb             1 non-null      float64
 81  CorrelateItemStatusCode     1 non-null      int64
dtypes: float64(25), int64(33), object(24)
memory usage: 784.0+ bytes

Eliminating unwanted columns - mostly descriptive columns

In [16]:
if RAW:
  d(diff_list(list(df1.columns), list(df2.columns)))

82 62

['OrderNumbert',
 'TransactionDate',
 'DepartmentName',
 'CategoryName',
 'GroupName',
 'SubGroupName',
 'CompoundIDDesc',
 'ProductDescription',
 'VendorName',
 'ItemsPerPackageWH',
 'DescriptionTavit',
 'DepartmentNameSusb',
 'CategoryNameSubs',
 'GroupNameSubs',
 'SubGroupNameSubs',
 'CompoundIDDescSubs',
 'ProductDescriptionSubs',
 'VendorNameSubs',
 'ItemsPerPackageWHSubs',
 'DescriptionTavitSubs']

In [17]:
if RAW:
  d(df2.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 37910 entries, 0 to 37909
Data columns (total 62 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   HouseHoldID                 37910 non-null  int64
 1   LocationCityName            37898 non-null  object
 2   QuarterNumber               37910 non-null  int64
 3   MonthNumber                 37910 non-null  int64
 4   WeekNumber                  37910 non-null  int64
 5   DayNumberInWeek             37910 non-null  int64
 6   PeriodHoliday               37910 non-null  object
 7   DepartmentCode              37910 non-null  int64
 8   CategoryCode                37910 non-null  int64
 9   GroupCode                   37910 non-null  int64
 10  SubGroupCode                37910 non-null  int64
 11  CompoundID                  37910 non-null  int64
 12  ParentProductNumber         37910 non-null  int64
 13  BrandIndDesc                37908 non-null  object
 14  BrandName                   37910 non-null  object
 15  VendorNumber                37910 non-null  int64
 16  UnitOfMeasure               37910 non-null  float64
 17  Price                       37910 non-null  float64
 18  Quantity                    37910 non-null  int64
 19  cntPrdAll                   37910 non-null  int64
 20  NetSaleAmountAll            37910 non-null  float64
 21  NetSaleNoVatPrdLast3Months  37902 non-null  float64
 22  QuantSale                   37073 non-null  float64
 23  cntMonths                   37910 non-null  int64
 24  DiscountPerUnit             18166 non-null  float64
 25  isPromo                     37910 non-null  object
 26  Energy                      33321 non-null  float64
 27  Pachmema                    27257 non-null  float64
 28  Natran                      32350 non-null  float64
 29  Helbon                      31977 non-null  float64
 30  Shuman                      24886 non-null  float64
 31  ShumanRavuy                 10951 non-null  float64
 32  ShumanTrans                 9215 non-null   float64
 33  Colastrol                   9328 non-null   float64
 34  SivimTzunatim               7175 non-null   float64
 35  CafiotSucar                 3820 non-null   float64
 36  DepartmentCodeSubs          37910 non-null  int64
 37  CategoryCodeSubs            37910 non-null  int64
 38  GroupCodeSubs               37910 non-null  int64
 39  SubGroupCodeSubs            37910 non-null  int64
 40  CompoundIDSubs              37910 non-null  int64
 41  ProductNumberSubs           37910 non-null  int64
 42  BrandIndDescSuss            37908 non-null  object
 43  BrandNameSubs               37910 non-null  object
 44  VendorNumberSubs            37909 non-null  float64
 45  UnitOfMeasureSubs           37910 non-null  float64
 46  PriceSubs                   37910 non-null  float64
 47  NetSaleNoVatPrdSubs         37428 non-null  float64
 48  QuantSaleSubs               37490 non-null  float64
 49  cntMonthsSubs               37910 non-null  int64
 50  DiscountPerUnitSubs         324 non-null    float64
 51  EnergySubs                  33370 non-null  float64
 52  PachmemaSubs                27023 non-null  float64
 53  NatranSubs                  32270 non-null  float64
 54  HelbonSubs                  31769 non-null  float64
 55  ShumanSubs                  17109 non-null  float64
 56  ShumanRavuySubs             10480 non-null  float64
 57  ShumanTransSubs             10203 non-null  float64
 58  ColastrolSubs               12976 non-null  float64
 59  SivimTzunatimSubs           11964 non-null  float64
 60  CafiotSucarSusb             6653 non-null   float64
 61  CorrelateItemStatusCode     37910 non-null  int64
dtypes: float64(32), int64(23), object(7)
memory usage: 17.9+ MB

None

In [18]:
# Fix Typo mistake
if RAW: 
  df2.rename(columns={'OrderNumbert': 'OrderNumber','BrandIndDescSuss': 'BrandIndDescSubs', 'ProductNumberSubs': 'ParentProductNumberSubs', 
                    'NetSaleNoVatPrdSubs': 'NetSaleNoVatPrdLast3MonthsSubs', 'CafiotSucarSusb': 'CafiotSucarSubs'}, inplace=True)

Eliminating nulls

In [19]:
# Fill na
if RAW:
  df2.fillna({'QuantSale': 1, 'QuantSaleSubs': 1}, inplace=True)
  df2.fillna(0, inplace=True)
  d(df2.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 37910 entries, 0 to 37909
Data columns (total 62 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   HouseHoldID                     37910 non-null  int64
 1   LocationCityName                37910 non-null  object
 2   QuarterNumber                   37910 non-null  int64
 3   MonthNumber                     37910 non-null  int64
 4   WeekNumber                      37910 non-null  int64
 5   DayNumberInWeek                 37910 non-null  int64
 6   PeriodHoliday                   37910 non-null  object
 7   DepartmentCode                  37910 non-null  int64
 8   CategoryCode                    37910 non-null  int64
 9   GroupCode                       37910 non-null  int64
 10  SubGroupCode                    37910 non-null  int64
 11  CompoundID                      37910 non-null  int64
 12  ParentProductNumber             37910 non-null  int64
 13  BrandIndDesc                    37910 non-null  object
 14  BrandName                       37910 non-null  object
 15  VendorNumber                    37910 non-null  int64
 16  UnitOfMeasure                   37910 non-null  float64
 17  Price                           37910 non-null  float64
 18  Quantity                        37910 non-null  int64
 19  cntPrdAll                       37910 non-null  int64
 20  NetSaleAmountAll                37910 non-null  float64
 21  NetSaleNoVatPrdLast3Months      37910 non-null  float64
 22  QuantSale                       37910 non-null  float64
 23  cntMonths                       37910 non-null  int64
 24  DiscountPerUnit                 37910 non-null  float64
 25  isPromo                         37910 non-null  object
 26  Energy                          37910 non-null  float64
 27  Pachmema                        37910 non-null  float64
 28  Natran                          37910 non-null  float64
 29  Helbon                          37910 non-null  float64
 30  Shuman                          37910 non-null  float64
 31  ShumanRavuy                     37910 non-null  float64
 32  ShumanTrans                     37910 non-null  float64
 33  Colastrol                       37910 non-null  float64
 34  SivimTzunatim                   37910 non-null  float64
 35  CafiotSucar                     37910 non-null  float64
 36  DepartmentCodeSubs              37910 non-null  int64
 37  CategoryCodeSubs                37910 non-null  int64
 38  GroupCodeSubs                   37910 non-null  int64
 39  SubGroupCodeSubs                37910 non-null  int64
 40  CompoundIDSubs                  37910 non-null  int64
 41  ParentProductNumberSubs         37910 non-null  int64
 42  BrandIndDescSubs                37910 non-null  object
 43  BrandNameSubs                   37910 non-null  object
 44  VendorNumberSubs                37910 non-null  float64
 45  UnitOfMeasureSubs               37910 non-null  float64
 46  PriceSubs                       37910 non-null  float64
 47  NetSaleNoVatPrdLast3MonthsSubs  37910 non-null  float64
 48  QuantSaleSubs                   37910 non-null  float64
 49  cntMonthsSubs                   37910 non-null  int64
 50  DiscountPerUnitSubs             37910 non-null  float64
 51  EnergySubs                      37910 non-null  float64
 52  PachmemaSubs                    37910 non-null  float64
 53  NatranSubs                      37910 non-null  float64
 54  HelbonSubs                      37910 non-null  float64
 55  ShumanSubs                      37910 non-null  float64
 56  ShumanRavuySubs                 37910 non-null  float64
 57  ShumanTransSubs                 37910 non-null  float64
 58  ColastrolSubs                   37910 non-null  float64
 59  SivimTzunatimSubs               37910 non-null  float64
 60  CafiotSucarSubs                 37910 non-null  float64
 61  CorrelateItemStatusCode         37910 non-null  int64
dtypes: float64(32), int64(23), object(7)
memory usage: 17.9+ MB

None

In [20]:
if RAW and False:
  df2.to_csv(prefix + ".csv", index = False)
  p(df2.shape)

In [21]:
if RAW and False:
  df = pd.read_csv(prefix + '.csv', index_col=False)
else:
  df = df2.copy()
p(df.shape)

(37910, 62)

## Encoding categories

In [22]:
from sklearn.preprocessing import LabelEncoder
enc = LabelEncoder()

if RAW:
  enc.fit(['PromoSusbDiffPromo', 'PromoSusbSamePromo', 'noPromo'])
  p(df.isPromo.value_counts())
  p()
  df.isPromo = enc.transform(df.isPromo)
  p(df.isPromo.value_counts())

noPromo               19744
PromoSusbDiffPromo    18059
PromoSusbSamePromo      107
Name: isPromo, dtype: int64

2    19744
0    18059
1      107
Name: isPromo, dtype: int64

In [27]:
if RAW:
  df['LocationCityName'] = df['LocationCityName'].astype('str')
  df['BrandIndDesc'] = df['BrandIndDesc'].astype('str')
  for col in ['LocationCityName', 'PeriodHoliday', 'BrandIndDesc', 'BrandName', 'BrandIndDescSubs', 'BrandNameSubs']:
    p(col)
    p(pd.DataFrame(df[col].value_counts()).index)
    df[col] = enc.fit_transform(df[col])
    p(pd.DataFrame(df[col].value_counts()).index)

LocationCityName
Index(['87', '98', '88', '38', '24', '94', '35', '66', '54', '85', '58', '92',
       '22', '93', '31', '34', '44', '67', '89', '15', '18', '62', '96', '19',
       '82', '21', '41', '84', '29', '91', '26', '20', '8', '61', '71', '6',
       '83', '74', '46', '10', '99', '90', '33', '30', '79', '43', '65', '63',
       '25', '77', '4', '56', '51', '52', '48', '78', '64', '12', '11', '80',
       '95', '2', '39', '13', '50', '40', '9', '5', '1', '45', '14', '55',
       '42', '16', '28', '81', '73', '0', '23', '59', '3', '97', '72', '36',
       '70', '7', '49', '27', '68', '53', '47', '69', '37', '76', '32', '86',
       '75', '17', '60', '57'],
      dtype='object')
Int64Index([86, 98, 87, 32, 17, 94, 29, 63, 50, 84, 54, 92, 15, 93, 25, 28, 39,
            64, 88,  7, 10, 59, 11, 96, 81, 14, 36, 83, 22, 91, 13, 19, 58, 78,
            69, 56, 82, 72, 41,  2, 99, 24, 27, 90, 77, 38, 62, 60, 18, 75, 34,
            47, 52, 48, 43, 76, 61,  4, 79,  3, 95, 12, 33,  5, 46, 35, 89, 45,
             6,  1, 40, 51,  8, 37, 21, 71, 80,  0, 16, 55, 97, 23, 70, 68, 30,
            67, 20, 44, 65, 31, 66, 49, 42, 85, 74, 26,  9, 73, 57, 53],
           dtype='int64')
PeriodHoliday
Int64Index([1, 0], dtype='int64')
Int64Index([1, 0], dtype='int64')
BrandIndDesc
Index(['2', '23', '45', '11', '16', '5', '34', '31', '13', '36', '46', '28',
       '32', '44', '27', '6', '14', '17', '26', '9', '12', '18', '19', '25',
       '38', '40', '3', '30', '29', '4', '10', '33', '1', '20', '35', '37',
       '7', '39', '24', '21', '43', '42', '15', '8', '22', '41', '0'],
      dtype='object')
Int64Index([12, 16, 40,  3,  8, 42, 28, 25,  5, 30, 41, 21, 26, 39, 20, 43,  6,
             9, 19, 46,  4, 10, 11, 18, 32, 35, 23, 24, 22, 34,  2, 27,  1, 13,
            29, 31, 44, 14, 33, 17, 37, 38,  7, 45, 15, 36,  0],
           dtype='int64')
BrandName
Int64Index([0, 1], dtype='int64')
Int64Index([0, 1], dtype='int64')
BrandIndDescSubs
Int64Index([61, 34, 47, 25,  8,  2, 43, 53,  9, 21, 19, 27, 64, 28, 39, 40, 15,
            60, 45, 38, 22, 20, 57,  4, 42, 36, 62,  3, 29, 55, 31, 50,  1, 18,
            12, 26, 46, 35, 24, 51, 59, 17, 41, 63, 49, 58, 54, 33, 56,  0, 13,
            32, 30, 23, 52, 10, 11,  5, 37,  6, 16,  7, 14, 44, 48],
           dtype='int64')
Int64Index([61, 34, 47, 25,  8,  2, 43, 53,  9, 21, 19, 27, 64, 28, 39, 40, 15,
            60, 45, 38, 22, 20, 57,  4, 42, 36, 62,  3, 29, 55, 31, 50,  1, 18,
            12, 26, 46, 35, 24, 51, 59, 17, 41, 63, 49, 58, 54, 33, 56,  0, 13,
            32, 30, 23, 52, 10, 11,  5, 37,  6, 16,  7, 14, 44, 48],
           dtype='int64')
BrandNameSubs
Int64Index([0, 1], dtype='int64')
Int64Index([0, 1], dtype='int64')

## Combine 'GroupCode' and 'SubGroupCode' into one column

In [28]:
if RAW:
  d(df.head(2))
  df.SubGroupCode = df.GroupCode * 10 + df.SubGroupCode
  df.SubGroupCodeSubs = df.GroupCodeSubs * 10 + df.SubGroupCodeSubs
#  df.drop(['SubGroupCode', 'SubGroupCodeSubs'], axis=1, inplace=True)
  d(df.head(2))

,HouseHoldID,LocationCityName,QuarterNumber,MonthNumber,WeekNumber,DayNumberInWeek,PeriodHoliday,DepartmentCode,CategoryCode,GroupCode,SubGroupCode,CompoundID,ParentProductNumber,BrandIndDesc,BrandName,VendorNumber,UnitOfMeasure,Price,Quantity,cntPrdAll,NetSaleAmountAll,NetSaleNoVatPrdLast3Months,QuantSale,cntMonths,DiscountPerUnit,isPromo,Energy,Pachmema,Natran,Helbon,Shuman,ShumanRavuy,ShumanTrans,Colastrol,SivimTzunatim,CafiotSucar,DepartmentCodeSubs,CategoryCodeSubs,GroupCodeSubs,SubGroupCodeSubs,CompoundIDSubs,ParentProductNumberSubs,BrandIndDescSubs,BrandNameSubs,VendorNumberSubs,UnitOfMeasureSubs,PriceSubs,NetSaleNoVatPrdLast3MonthsSubs,QuantSaleSubs,cntMonthsSubs,DiscountPerUnitSubs,EnergySubs,PachmemaSubs,NatranSubs,HelbonSubs,ShumanSubs,ShumanRavuySubs,ShumanTransSubs,ColastrolSubs,SivimTzunatimSubs,CafiotSucarSubs,CorrelateItemStatusCode
0,1,98,202101,202103,202110,4,1,10,1,640,4,-8005110170300,8005110170300,12,0,913847,1.20,10.0,2,46,879.75,1148095.31,0.2,16,6.89,0,26.0,3.9,120.0,1.2,0.2,0.0,0.0,0.0,0.0,0.0,10,1,640,4,-7296073414278,7296073414278,61,1,921174.0,1.20,10.0,118719.70,0.6,9,0.0,26.0,4.2,114.0,1.6,0.0,0.0,0.0,0.0,1.5,0.75,1
1,2,86,202101,202103,202112,5,0,10,1,703,4,-4165017,4165017,8,0,921279,0.56,5.9,1,42,618.73,16230.05,1.0,17,0.00,2,43.0,10.0,15.0,0.2,0.2,0.0,0.0,0.0,1.2,0.0,10,1,703,4,14011,2881216,64,0,921169.0,0.72,10.0,21056.56,1.0,17,0.0,51.0,11.5,0.0,0.0,0.0,0.0,0.0,0.0,1.4,2.50,1

,HouseHoldID,LocationCityName,QuarterNumber,MonthNumber,WeekNumber,DayNumberInWeek,PeriodHoliday,DepartmentCode,CategoryCode,GroupCode,SubGroupCode,CompoundID,ParentProductNumber,BrandIndDesc,BrandName,VendorNumber,UnitOfMeasure,Price,Quantity,cntPrdAll,NetSaleAmountAll,NetSaleNoVatPrdLast3Months,QuantSale,cntMonths,DiscountPerUnit,isPromo,Energy,Pachmema,Natran,Helbon,Shuman,ShumanRavuy,ShumanTrans,Colastrol,SivimTzunatim,CafiotSucar,DepartmentCodeSubs,CategoryCodeSubs,GroupCodeSubs,SubGroupCodeSubs,CompoundIDSubs,ParentProductNumberSubs,BrandIndDescSubs,BrandNameSubs,VendorNumberSubs,UnitOfMeasureSubs,PriceSubs,NetSaleNoVatPrdLast3MonthsSubs,QuantSaleSubs,cntMonthsSubs,DiscountPerUnitSubs,EnergySubs,PachmemaSubs,NatranSubs,HelbonSubs,ShumanSubs,ShumanRavuySubs,ShumanTransSubs,ColastrolSubs,SivimTzunatimSubs,CafiotSucarSubs,CorrelateItemStatusCode
0,1,98,202101,202103,202110,4,1,10,1,640,6404,-8005110170300,8005110170300,12,0,913847,1.20,10.0,2,46,879.75,1148095.31,0.2,16,6.89,0,26.0,3.9,120.0,1.2,0.2,0.0,0.0,0.0,0.0,0.0,10,1,640,6404,-7296073414278,7296073414278,61,1,921174.0,1.20,10.0,118719.70,0.6,9,0.0,26.0,4.2,114.0,1.6,0.0,0.0,0.0,0.0,1.5,0.75,1
1,2,86,202101,202103,202112,5,0,10,1,703,7034,-4165017,4165017,8,0,921279,0.56,5.9,1,42,618.73,16230.05,1.0,17,0.00,2,43.0,10.0,15.0,0.2,0.2,0.0,0.0,0.0,1.2,0.0,10,1,703,7034,14011,2881216,64,0,921169.0,0.72,10.0,21056.56,1.0,17,0.0,51.0,11.5,0.0,0.0,0.0,0.0,0.0,0.0,1.4,2.50,1

## Use Dummies

Minimal improvement - FalseNegative (0,0) improved from 1338 to 1328

In [29]:
## Converting the categories column (isPromo) to dummies column 
if RAW:
  p(df.shape)
  df = pd.get_dummies(df, columns=['isPromo', 'PeriodHoliday'])
  p(df.shape)

(37910, 62)
(37910, 65)

In [30]:
if RAW:
  df_t = df.copy()

## Calc diff vector

In [31]:
if RAW:
  p(df.columns)

Index(['HouseHoldID', 'LocationCityName', 'QuarterNumber', 'MonthNumber',
       'WeekNumber', 'DayNumberInWeek', 'DepartmentCode', 'CategoryCode',
       'GroupCode', 'SubGroupCode', 'CompoundID', 'ParentProductNumber',
       'BrandIndDesc', 'BrandName', 'VendorNumber', 'UnitOfMeasure', 'Price',
       'Quantity', 'cntPrdAll', 'NetSaleAmountAll',
       'NetSaleNoVatPrdLast3Months', 'QuantSale', 'cntMonths',
       'DiscountPerUnit', 'Energy', 'Pachmema', 'Natran', 'Helbon', 'Shuman',
       'ShumanRavuy', 'ShumanTrans', 'Colastrol', 'SivimTzunatim',
       'CafiotSucar', 'DepartmentCodeSubs', 'CategoryCodeSubs',
       'GroupCodeSubs', 'SubGroupCodeSubs', 'CompoundIDSubs',
       'ParentProductNumberSubs', 'BrandIndDescSubs', 'BrandNameSubs',
       'VendorNumberSubs', 'UnitOfMeasureSubs', 'PriceSubs',
       'NetSaleNoVatPrdLast3MonthsSubs', 'QuantSaleSubs', 'cntMonthsSubs',
       'DiscountPerUnitSubs', 'EnergySubs', 'PachmemaSubs', 'NatranSubs',
       'HelbonSubs', 'ShumanSubs', 'ShumanRavuySubs', 'ShumanTransSubs',
       'ColastrolSubs', 'SivimTzunatimSubs', 'CafiotSucarSubs',
       'CorrelateItemStatusCode', 'isPromo_0', 'isPromo_1', 'isPromo_2',
       'PeriodHoliday_0', 'PeriodHoliday_1'],
      dtype='object')

In [32]:
if RAW and DIFF:
  for col in ['DepartmentCode', 'CategoryCode', 'GroupCode', #'SubGroupCode',
       'CompoundID', 'ParentProductNumber', 'BrandIndDesc',
       'VendorNumber', 'UnitOfMeasure', 'Price', 'NetSaleNoVatPrdLast3Months', 'Energy', 'Pachmema',
       'Natran', 'Helbon', 'Shuman', 'ShumanRavuy', 'ShumanTrans', 'Colastrol',
       'SivimTzunatim', 'CafiotSucar', 'QuantSale', 'cntMonths', 'DiscountPerUnit']:
    df[col + 'Diff'] = df[col] - df[col + 'Subs']

In [33]:
if RAW and DIFF:
  for col in ['DepartmentCode', 'CategoryCode', 'GroupCode', #'SubGroupCode',
       'CompoundID', 'ParentProductNumber', 'VendorNumber', 'BrandIndDesc']:
    df[col + 'Diff'] = (df[col + 'Diff'] != 0)    # tested both ==0 and !=0 (the result is 1 for one and 0 for the other - no change in the model results)
    df[col + 'Diff'] = enc.fit_transform(df[col + 'Diff'])

In [34]:
if RAW and DIFF:
  df.to_csv(prefix + "_with_diff.csv", index = False)

In [35]:
if RAW and DIFF:
  df = pd.read_csv(prefix + '_with_diff.csv', index_col=False)
  p(df.shape)

# Get ready Data

In [36]:
if RAW:
  p(df.shape)
  d(df.head())

(37910, 65)

,HouseHoldID,LocationCityName,QuarterNumber,MonthNumber,WeekNumber,DayNumberInWeek,DepartmentCode,CategoryCode,GroupCode,SubGroupCode,CompoundID,ParentProductNumber,BrandIndDesc,BrandName,VendorNumber,UnitOfMeasure,Price,Quantity,cntPrdAll,NetSaleAmountAll,NetSaleNoVatPrdLast3Months,QuantSale,cntMonths,DiscountPerUnit,Energy,Pachmema,Natran,Helbon,Shuman,ShumanRavuy,ShumanTrans,Colastrol,SivimTzunatim,CafiotSucar,DepartmentCodeSubs,CategoryCodeSubs,GroupCodeSubs,SubGroupCodeSubs,CompoundIDSubs,ParentProductNumberSubs,BrandIndDescSubs,BrandNameSubs,VendorNumberSubs,UnitOfMeasureSubs,PriceSubs,NetSaleNoVatPrdLast3MonthsSubs,QuantSaleSubs,cntMonthsSubs,DiscountPerUnitSubs,EnergySubs,PachmemaSubs,NatranSubs,HelbonSubs,ShumanSubs,ShumanRavuySubs,ShumanTransSubs,ColastrolSubs,SivimTzunatimSubs,CafiotSucarSubs,CorrelateItemStatusCode,isPromo_0,isPromo_1,isPromo_2,PeriodHoliday_0,PeriodHoliday_1
0,1,98,202101,202103,202110,4,10,1,640,6404,-8005110170300,8005110170300,12,0,913847,1.20,10.0,2,46,879.75,1148095.31,0.2,16,6.890,26.0,3.9,120.0,1.2,0.2,0.0,0.0,0.0,0.0,0.0,10,1,640,6404,-7296073414278,7296073414278,61,1,921174.0,1.20,10.0,118719.70,0.6,9,0.0,26.0,4.2,114.0,1.6,0.0,0.0,0.0,0.0,1.5,0.75,1,1,0,0,0,1
1,2,86,202101,202103,202112,5,10,1,703,7034,-4165017,4165017,8,0,921279,0.56,5.9,1,42,618.73,16230.05,1.0,17,0.000,43.0,10.0,15.0,0.2,0.2,0.0,0.0,0.0,1.2,0.0,10,1,703,7034,14011,2881216,64,0,921169.0,0.72,10.0,21056.56,1.0,17,0.0,51.0,11.5,0.0,0.0,0.0,0.0,0.0,0.0,1.4,2.50,1,0,0,1,1,0
2,3,17,202101,202103,202110,2,10,1,640,6404,-8005110170300,8005110170300,12,0,913847,1.20,10.0,1,43,946.07,1148095.31,0.2,16,6.895,26.0,3.9,120.0,1.2,0.2,0.0,0.0,0.0,0.0,0.0,10,1,640,6407,42423,7290014083561,15,0,912043.0,1.20,10.0,0.00,1.0,3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0,1,0,0,0,1
3,4,86,202101,202103,202112,4,10,1,640,6404,-8005110170300,8005110170300,12,0,913847,1.20,10.0,2,65,1207.23,1148095.31,0.2,16,6.896,26.0,3.9,120.0,1.2,0.2,0.0,0.0,0.0,0.0,0.0,10,1,640,6404,-7290016087499,7290016087499,47,0,920285.0,1.20,10.0,9628.09,1.0,17,0.0,20.0,4.0,25.0,1.1,0.0,0.0,0.0,2.5,0.0,0.00,1,1,0,0,1,0
4,5,86,202101,202103,202111,5,10,1,640,6404,-8005110170300,8005110170300,12,0,913847,1.20,10.0,1,81,1396.98,1148095.31,0.2,16,6.875,26.0,3.9,120.0,1.2,0.2,0.0,0.0,0.0,0.0,0.0,10,1,640,6404,-7296073414278,7296073414278,61,1,921174.0,1.20,10.0,118719.70,0.6,9,0.0,26.0,4.2,114.0,1.6,0.0,0.0,0.0,0.0,1.5,0.75,1,1,0,0,1,0

In [37]:
if not RAW:
  df = pd.read_csv(prefix + '_with_diff.csv', encoding='ISO-8859-8')
  p(df.shape)
  d(df.head())

# Models

In [42]:
REMOVE_ING = False
SPLIT_DATE = False
ONLY_PRICE = False
GS = False
CV = False

SWEETS = False

## Models - remove ingredients - no change in results

In [39]:
if REMOVE_ING:
  id = 'remove_ingredients'
  try:
    del X_train, X_test, y_train, y_test
  except:
    pass
  
  cols = ['CorrelateItemStatusCode']
  for col in ['Energy', 'Pachmema', 'Natran', 'Helbon', 'Shuman', 'ShumanRavuy', 'ShumanTrans', 'Colastrol',
       'SivimTzunatim', 'CafiotSucar']:
      cols.append(col)
      cols.append(col + 'Subs')
      cols.append(col + 'Diff')

  X = df.drop(cols, axis=1)
  y = df.CorrelateItemStatusCode.astype(int)

  X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.7, random_state=0)
  p(df.shape)
  p(X_train.shape, X_test.shape, y_train.shape, y_test.shape)

(37912, 88)

(26538, 57) (11374, 57) (26538,) (11374,)

## Models - remove all features execpt of prices

In [40]:
if ONLY_PRICE:
  id = 'only_prices'
  try:
    del X_train, X_test, y_train, y_test
  except:
    pass
  
  X = df[['Price', 'PriceSubs', 'PriceDiff']]
  y = df.CorrelateItemStatusCode.astype(int)

  X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.7, random_state=0)
  p(df.shape)
  p(X_train.shape, X_test.shape, y_train.shape, y_test.shape)

(37912, 88)

(26538, 3) (11374, 3) (26538,) (11374,)

## Models - Train on sweets, test on cans

In [43]:
if SWEETS:
  get_raw('Shufersal_with_diff.csv')
  df = pd.read_csv('Shufersal_with_diff.csv', index_col=False)
  p(df.shape)
  d(df.head(1))

In [44]:
if SWEETS:
  df_sweets = pd.read_csv('Shufersal_with_diff.csv', index_col=False)
  X_train = df_sweets.drop('CorrelateItemStatusCode', axis=1)
  y_train = df_sweets.CorrelateItemStatusCode.astype(int)

  p(df_sweets.shape, X_train.shape, y_train.shape)
  d(df_sweets.head())

In [45]:
if SWEETS:
  df_cans = pd.read_csv(prefix + '_with_diff.csv', index_col=False)
  X_test = df_cans.drop('CorrelateItemStatusCode', axis=1)
  y_test = df_cans.CorrelateItemStatusCode.astype(int)

  p(df_cans.shape, X_test.shape, y_test.shape)
  d(df_cans.head())

  id = 'train_sweet_pred_cans'


## Models - process_model code

In [46]:
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score
import math

pd.set_option("precision", 2)
df_result = pd.DataFrame()

In [47]:
from sklearn.model_selection import train_test_split, GridSearchCV, cross_val_score

X = df.drop('CorrelateItemStatusCode', axis=1)
y = df.CorrelateItemStatusCode.astype(int)

X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.7, random_state=0)

In [48]:
def report(clf, X, y, note, test, data_type='Test'):
  global df_result
  name = type(clf).__name__ + ': ' + data_type
  acc = accuracy_score(y_true=y, y_pred=clf.predict(X))
  index = [(name, clf.classes_[0]), (name, clf.classes_[1])]
  cm = pd.DataFrame(confusion_matrix(y_true=y, y_pred=clf.predict(X)),
                    index=clf.classes_,
                    columns=clf.classes_)
  cm.reset_index(drop=True, inplace=True)
  rep = classification_report(y_true=y, y_pred=clf.predict(X), zero_division=1, output_dict=True)
  rep =  pd.DataFrame(rep)
  rep = rep.T
  rep['accuracy'] = acc
  rep.support = rep.support.astype(int)
  cols = list(rep.columns[:3]) + ['accuracy', 'support']
  rep = rep[cols]
  rep['precision_avg'] = rep.precision['macro avg']
  rep['recall_avg'] = rep.recall['macro avg']
  rep['f1-score_avg'] = rep['f1-score']['macro avg']
  rep.drop(['accuracy', 'macro avg', 'weighted avg'], axis=0, inplace=True)
  rep.reset_index(drop=True, inplace=True)
  df = cm.join(rep)
  df['name'] = name
  df['note'] = note
  df.loc[1, 'note'] = ''
  if test:  # do not add to database
    d(df)
  else:    
    df.reset_index(inplace=True)
    df_result.reset_index(inplace=True)
    df_result = df_result.append(df, ignore_index=True)
    df_result.set_index(['name', 'index'], inplace=True)
  return df_result

In [49]:
#ROC and AUC
from sklearn.metrics import roc_curve
from sklearn.metrics import roc_auc_score

def get_roc_and_auc(model,X_test,y_test):
    ns_probs = [0 for _ in range(len(y_test))]
#    lr_probs = clf_voting.predict_proba(X_test)[:,1]
    lr_probs = model.predict_proba(X_test)[:,1]
    ns_auc = roc_auc_score(y_test, ns_probs)
    lr_auc = roc_auc_score(y_test, lr_probs)
    # summarize scores
    print('\nNo Skill: ROC AUC=%.3f' % (ns_auc))
    print('model: ROC AUC=%.3f' % (lr_auc))
    # calculate roc curves
    ns_fpr, ns_tpr, _ = roc_curve(y_test, ns_probs)
    lr_fpr, lr_tpr, _ = roc_curve(y_test, lr_probs)
    # plot the roc curve for the model
    fig = plt.figure(figsize=(5,5))
    plt.plot(ns_fpr, ns_tpr, linestyle='--', label='No Skill')
    plt.plot(lr_fpr, lr_tpr, marker='.', label='model')
    # axis labels
    plt.xlabel('False Positive Rate')
    plt.ylabel('True Positive Rate')
    plt.title(type(model).__name__ )
    # show the legend
    plt.legend()
    # show the plot
    plt.show()

In [50]:
def showFeatureImportance(model, X, threshold):
  if type(model).__name__ == 'LogisticRegression':  # no features importance data
    w0 = model.intercept_[0]
    w = model.coef_[0]
    fx_imp = pd.Series(w, index=X.columns)
  else:
    fx_imp = pd.Series(model.feature_importances_, index=X.columns)
  fx_imp /= fx_imp.sum()
  fx_imp = fx_imp.sort_values()
  fx_imp = fx_imp[fx_imp > threshold]
  fig = plt.figure(figsize=(5,5))
  plt.xlim(0, 1)
  fx_imp.plot(kind='barh', title=type(model).__name__ )

In [51]:
def process_model(model, X, y, X_test, y_test, plot=False, threshold=0, note='', test=False):
  p('running: ', type(model).__name__, X.shape)
  model.fit(X, y)
  report(model, X, y, note, test, 'Train')
  report(model, X_test, y_test, note, test)
  if plot:
    showFeatureImportance(model, X, threshold)
    get_roc_and_auc(model,X_test,y_test)    
  return df_result

In [52]:
from sklearn.linear_model import LogisticRegression, BayesianRidge, Lasso, Ridge
from sklearn.ensemble import GradientBoostingClassifier, RandomForestClassifier, AdaBoostClassifier, GradientBoostingRegressor, BaggingClassifier, VotingClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import LinearSVC


## Models - Run process_model

In [53]:
df_result = pd.DataFrame()

clf_RF = RandomForestClassifier(n_estimators=200, criterion='entropy', max_depth=None, min_samples_split=20, ccp_alpha=0.0003, random_state=73)
process_model(clf_RF, X_train, y_train, X_test, y_test, plot=False, threshold=0.015, note="n_estimators=200, criterion='entropy', max_depth=None, min_samples_split=20, ccp_alpha=0.0003, random_state=73")


d(df_result)

fname = prefix + f'_result_{id}.csv'
df_result.to_csv(fname, index = True)

running:  RandomForestClassifier (26537, 64)

                                          0        1  precision  recall  \
name                          index
RandomForestClassifier: Train 0      8137.0   2511.0       0.90    0.76
                              1       880.0  15009.0       0.86    0.94
RandomForestClassifier: Test  0      3238.0   1319.0       0.86    0.71
                              1       529.0   6287.0       0.83    0.92

                                     f1-score  accuracy  support  \
name                          index
RandomForestClassifier: Train 0          0.83      0.87  10648.0
                              1          0.90      0.87  15889.0
RandomForestClassifier: Test  0          0.78      0.84   4557.0
                              1          0.87      0.84   6816.0

                                     precision_avg  recall_avg  f1-score_avg  \
name                          index
RandomForestClassifier: Train 0               0.88        0.85          0.86
                              1               0.88        0.85          0.86
RandomForestClassifier: Test  0               0.84        0.82          0.82
                              1               0.84        0.82          0.82

                                                                                  note
name                          index
RandomForestClassifier: Train 0      n_estimators=200, criterion='entropy', max_dep...
                              1
RandomForestClassifier: Test  0      n_estimators=200, criterion='entropy', max_dep...
                              1

## Models - compare results

1. Diff
2. Diff with remove ingredients columns
6. OnlyPrices - Diff with only 3 features( Price, PriceSubs, PriceDiff)
7. Train on sweets, predict on cans
8. No Diff (no comparison between master and subs)

In [54]:
def read_results(id='', disp=True, full=False):
  fname = prefix + f'_result_{id}.csv'
  p(fname)
  try:
    df = pd.read_csv(fname)
  except:
    try:
      df = get_raw(fname, 'Results/')
#      df = pd.read_csv(fname)
    except:
      p('No data')
      return
  df.set_index(['name', 'index'], inplace=True)
  if not full:
    df = df.loc[['RandomForestClassifier: Train', 'RandomForestClassifier: Test']]#.copy()
  if disp:
    pd.set_option("max_column", 120)
    d(df)
  return df

In [55]:
p(id)
read_results()
read_results('remove_ingredients')
read_results('only_prices')
read_results('train_sweet_pred_cans')
read_results('no_diff')
p()

no_diff
Shufersal_cans_result_.csv

                                          0        1  precision  recall  \
name                          index
RandomForestClassifier: Train 0      8245.0   2395.0       0.89    0.77
                              1       990.0  14908.0       0.86    0.94
RandomForestClassifier: Test  0      3329.0   1237.0       0.86    0.73
                              1       550.0   6258.0       0.83    0.92

                                     f1-score  accuracy  support  \
name                          index
RandomForestClassifier: Train 0          0.83      0.87  10640.0
                              1          0.90      0.87  15898.0
RandomForestClassifier: Test  0          0.79      0.84   4566.0
                              1          0.88      0.84   6808.0

                                     precision_avg  recall_avg  f1-score_avg  \
name                          index
RandomForestClassifier: Train 0               0.88        0.86          0.86
                              1               0.88        0.86          0.86
RandomForestClassifier: Test  0               0.85        0.82          0.83
                              1               0.85        0.82          0.83

                                                                                  note
name                          index
RandomForestClassifier: Train 0      n_estimators=200, criterion='entropy', max_dep...
                              1                                                    NaN
RandomForestClassifier: Test  0      n_estimators=200, criterion='entropy', max_dep...
                              1                                                    NaN

Shufersal_cans_result_remove_ingredients.csv

                                          0        1  precision  recall  \
name                          index
RandomForestClassifier: Train 0      8238.0   2402.0       0.90    0.77
                              1       926.0  14972.0       0.86    0.94
RandomForestClassifier: Test  0      3321.0   1245.0       0.86    0.73
                              1       524.0   6284.0       0.83    0.92

                                     f1-score  accuracy  support  \
name                          index
RandomForestClassifier: Train 0          0.83      0.87  10640.0
                              1          0.90      0.87  15898.0
RandomForestClassifier: Test  0          0.79      0.84   4566.0
                              1          0.88      0.84   6808.0

                                     precision_avg  recall_avg  f1-score_avg  \
name                          index
RandomForestClassifier: Train 0               0.88        0.86          0.87
                              1               0.88        0.86          0.87
RandomForestClassifier: Test  0               0.85        0.83          0.83
                              1               0.85        0.83          0.83

                                                                                  note
name                          index
RandomForestClassifier: Train 0      n_estimators=200, criterion='entropy', max_dep...
                              1                                                    NaN
RandomForestClassifier: Test  0      n_estimators=200, criterion='entropy', max_dep...
                              1                                                    NaN

Shufersal_cans_result_only_prices.csv

                                          0        1  precision  recall  \
name                          index
RandomForestClassifier: Train 0      7782.0   2858.0       0.79    0.73
                              1      2060.0  13838.0       0.83    0.87
RandomForestClassifier: Test  0      3260.0   1306.0       0.78    0.71
                              1       938.0   5870.0       0.82    0.86

                                     f1-score  accuracy  support  \
name                          index
RandomForestClassifier: Train 0          0.76      0.81  10640.0
                              1          0.85      0.81  15898.0
RandomForestClassifier: Test  0          0.74      0.80   4566.0
                              1          0.84      0.80   6808.0

                                     precision_avg  recall_avg  f1-score_avg  \
name                          index
RandomForestClassifier: Train 0               0.81        0.80          0.80
                              1               0.81        0.80          0.80
RandomForestClassifier: Test  0               0.80        0.79          0.79
                              1               0.80        0.79          0.79

                                                                                  note
name                          index
RandomForestClassifier: Train 0      n_estimators=200, criterion='entropy', max_dep...
                              1                                                    NaN
RandomForestClassifier: Test  0      n_estimators=200, criterion='entropy', max_dep...
                              1                                                    NaN

Shufersal_cans_result_train_sweet_pred_cans.csv

                                           0        1  precision  recall  \
name                          index
RandomForestClassifier: Train 0      12719.0   5349.0       0.84    0.70
                              1       2412.0  33980.0       0.86    0.93
RandomForestClassifier: Test  0       9813.0   5393.0       0.67    0.65
                              1       4873.0  17833.0       0.77    0.79

                                     f1-score  accuracy  support  \
name                          index
RandomForestClassifier: Train 0          0.77      0.86  18068.0
                              1          0.90      0.86  36392.0
RandomForestClassifier: Test  0          0.66      0.73  15206.0
                              1          0.78      0.73  22706.0

                                     precision_avg  recall_avg  f1-score_avg  \
name                          index
RandomForestClassifier: Train 0               0.85        0.82          0.83
                              1               0.85        0.82          0.83
RandomForestClassifier: Test  0               0.72        0.72          0.72
                              1               0.72        0.72          0.72

                                                                                  note
name                          index
RandomForestClassifier: Train 0      n_estimators=200, criterion='entropy', max_dep...
                              1                                                    NaN
RandomForestClassifier: Test  0      n_estimators=200, criterion='entropy', max_dep...
                              1                                                    NaN

Shufersal_cans_result_no_diff.csv

                                          0        1  precision  recall  \
name                          index
RandomForestClassifier: Train 0      8137.0   2511.0       0.90    0.76
                              1       880.0  15009.0       0.86    0.94
RandomForestClassifier: Test  0      3238.0   1319.0       0.86    0.71
                              1       529.0   6287.0       0.83    0.92

                                     f1-score  accuracy  support  \
name                          index
RandomForestClassifier: Train 0          0.83      0.87  10648.0
                              1          0.90      0.87  15889.0
RandomForestClassifier: Test  0          0.78      0.84   4557.0
                              1          0.87      0.84   6816.0

                                     precision_avg  recall_avg  f1-score_avg  \
name                          index
RandomForestClassifier: Train 0               0.88        0.85          0.86
                              1               0.88        0.85          0.86
RandomForestClassifier: Test  0               0.84        0.82          0.82
                              1               0.84        0.82          0.82

                                                                                  note
name                          index
RandomForestClassifier: Train 0      n_estimators=200, criterion='entropy', max_dep...
                              1                                                    NaN
RandomForestClassifier: Test  0      n_estimators=200, criterion='entropy', max_dep...
                              1                                                    NaN