<a href="https://colab.research.google.com/github/DanielKorenDataScience/ClassificationProject/blob/main/Classification_Project_Shufersal_Cans.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Classification Project - CANS

for Shufersal on-line orders, for replacing of missing products, will predict the replacement success!

In [5]:
import requests
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

from IPython.display import display
p = print
d = display

# Get Data

## Raw Data

To run the raw section, one must load Sweets_ver2.csv to local google drive and change the next line to True

In [1]:
id = ''  # name of result file
prefix = 'Shufersal_cans'

RAW = True
DIFF = False

if not DIFF:
  id = 'no diff'

In [2]:
def get_raw(fname, subdir=''):
  data_url = 'https://raw.githubusercontent.com/DanielKorenDataScience/ClassificationProject/main/' + subdir + fname
  resp = requests.get(data_url)
  text = resp.text
  
  if len(text) > 100:
    with open(fname, 'w') as fh:
      fh.write(text)

In [3]:
def diff_list(li1, li2):
  p(len(li1), len(li2))
  return [i for i in li1 + li2 if i not in li1 or i not in li2]

In [6]:
if RAW:
  fname = 'Cans.csv'
  get_raw(fname)    
  df1 = pd.read_csv(fname, encoding='utf-8', nrows=1)
  df2 = pd.read_csv(fname, encoding='utf-8', usecols=[i for i in range(82) if not i in[0,8,10,12,14,16,18,20,24,26,27,48,50,52,54,56,58,62,64,65]])
  d(df1)

   OrderNumbert  HouseHoldID  ... CafiotSucarSusb  CorrelateItemStatusCode
0          5499            1  ...            0.75                        1

[1 rows x 82 columns]

### Cans dataset identical features as Sweets - the diff list returns empty list

In [ ]:
if RAW:
  fname = 'Sweets.csv'
  get_raw(fname)    
  df_sweet = pd.read_csv(fname, encoding='utf-8', nrows=1)
  d(diff_list(list(df1.columns), list(df_sweet.columns)))

82 82

[]

In [ ]:
if RAW:
  df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1 entries, 0 to 0
Data columns (total 82 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   OrderNumbert                1 non-null      int64
 1   HouseHoldID                 1 non-null      int64
 2   LocationCityName            1 non-null      object
 3   QuarterNumber               1 non-null      int64
 4   MonthNumber                 1 non-null      int64
 5   WeekNumber                  1 non-null      int64
 6   DayNumberInWeek             1 non-null      int64
 7   PeriodHoliday               1 non-null      object
 8   TransactionDate             1 non-null      object
 9   DepartmentCode              1 non-null      int64
 10  DepartmentName              1 non-null      object
 11  CategoryCode                1 non-null      int64
 12  CategoryName                1 non-null      object
 13  GroupCode                   1 non-null      int64
 14  GroupName                   1 non-null      object
 15  SubGroupCode                1 non-null      int64
 16  SubGroupName                1 non-null      object
 17  CompoundID                  1 non-null      float64
 18  CompoundIDDesc              1 non-null      object
 19  ParentProductNumber         1 non-null      float64
 20  ProductDescription          1 non-null      object
 21  BrandIndDesc                1 non-null      object
 22  BrandName                   1 non-null      object
 23  VendorNumber                1 non-null      int64
 24  VendorName                  1 non-null      object
 25  UnitOfMeasure               1 non-null      float64
 26  ItemsPerPackageWH           1 non-null      int64
 27  DescriptionTavit            1 non-null      object
 28  Price                       1 non-null      int64
 29  Quantity                    1 non-null      int64
 30  cntPrdAll                   1 non-null      int64
 31  NetSaleAmountAll            1 non-null      float64
 32  NetSaleNoVatPrdLast3Months  1 non-null      float64
 33  QuantSale                   1 non-null      float64
 34  cntMonths                   1 non-null      int64
 35  DiscountPerUnit             1 non-null      float64
 36  isPromo                     1 non-null      object
 37  Energy                      1 non-null      int64
 38  Pachmema                    1 non-null      float64
 39  Natran                      1 non-null      int64
 40  Helbon                      1 non-null      float64
 41  Shuman                      1 non-null      float64
 42  ShumanRavuy                 0 non-null      float64
 43  ShumanTrans                 0 non-null      float64
 44  Colastrol                   0 non-null      float64
 45  SivimTzunatim               0 non-null      float64
 46  CafiotSucar                 0 non-null      float64
 47  DepartmentCodeSubs          1 non-null      int64
 48  DepartmentNameSusb          1 non-null      object
 49  CategoryCodeSubs            1 non-null      int64
 50  CategoryNameSubs            1 non-null      object
 51  GroupCodeSubs               1 non-null      int64
 52  GroupNameSubs               1 non-null      object
 53  SubGroupCodeSubs            1 non-null      int64
 54  SubGroupNameSubs            1 non-null      object
 55  CompoundIDSubs              1 non-null      float64
 56  CompoundIDDescSubs          1 non-null      object
 57  ProductNumberSubs           1 non-null      float64
 58  ProductDescriptionSubs      1 non-null      object
 59  BrandIndDescSuss            1 non-null      object
 60  BrandNameSubs               1 non-null      object
 61  VendorNumberSubs            1 non-null      int64
 62  VendorNameSubs              1 non-null      object
 63  UnitOfMeasureSubs           1 non-null      float64
 64  ItemsPerPackageWHSubs       1 non-null      int64
 65  DescriptionTavitSubs        1 non-null      object
 66  PriceSubs                   1 non-null      int64
 67  NetSaleNoVatPrdSubs         1 non-null      float64
 68  QuantSaleSubs               1 non-null      float64
 69  cntMonthsSubs               1 non-null      int64
 70  DiscountPerUnitSubs         0 non-null      float64
 71  EnergySubs                  1 non-null      int64
 72  PachmemaSubs                1 non-null      float64
 73  NatranSubs                  1 non-null      int64
 74  HelbonSubs                  1 non-null      float64
 75  ShumanSubs                  0 non-null      float64
 76  ShumanRavuySubs             0 non-null      float64
 77  ShumanTransSubs             0 non-null      float64
 78  ColastrolSubs               0 non-null      float64
 79  SivimTzunatimSubs           1 non-null      float64
 80  CafiotSucarSusb             1 non-null      float64
 81  CorrelateItemStatusCode     1 non-null      int64
dtypes: float64(29), int64(29), object(24)
memory usage: 784.0+ bytes

Eliminating unwanted columns - mostly descriptive columns

In [ ]:
if RAW:
  d(diff_list(list(df1.columns), list(df2.columns)))

82 62

['OrderNumbert',
 'TransactionDate',
 'DepartmentName',
 'CategoryName',
 'GroupName',
 'SubGroupName',
 'CompoundIDDesc',
 'ProductDescription',
 'VendorName',
 'ItemsPerPackageWH',
 'DescriptionTavit',
 'DepartmentNameSusb',
 'CategoryNameSubs',
 'GroupNameSubs',
 'SubGroupNameSubs',
 'CompoundIDDescSubs',
 'ProductDescriptionSubs',
 'VendorNameSubs',
 'ItemsPerPackageWHSubs',
 'DescriptionTavitSubs']

In [ ]:
if RAW:
  d(df2.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 37912 entries, 0 to 37911
Data columns (total 62 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   HouseHoldID                 37912 non-null  int64
 1   LocationCityName            37904 non-null  object
 2   QuarterNumber               37912 non-null  int64
 3   MonthNumber                 37912 non-null  int64
 4   WeekNumber                  37912 non-null  int64
 5   DayNumberInWeek             37912 non-null  int64
 6   PeriodHoliday               37912 non-null  object
 7   DepartmentCode              37912 non-null  int64
 8   CategoryCode                37912 non-null  int64
 9   GroupCode                   37912 non-null  int64
 10  SubGroupCode                37912 non-null  int64
 11  CompoundID                  37912 non-null  float64
 12  ParentProductNumber         37912 non-null  float64
 13  BrandIndDesc                37910 non-null  object
 14  BrandName                   37912 non-null  object
 15  VendorNumber                37912 non-null  int64
 16  UnitOfMeasure               37912 non-null  float64
 17  Price                       37912 non-null  float64
 18  Quantity                    37912 non-null  int64
 19  cntPrdAll                   37912 non-null  int64
 20  NetSaleAmountAll            37912 non-null  float64
 21  NetSaleNoVatPrdLast3Months  37904 non-null  float64
 22  QuantSale                   37075 non-null  float64
 23  cntMonths                   37912 non-null  int64
 24  DiscountPerUnit             18166 non-null  float64
 25  isPromo                     37912 non-null  object
 26  Energy                      33323 non-null  float64
 27  Pachmema                    27259 non-null  float64
 28  Natran                      32352 non-null  float64
 29  Helbon                      31978 non-null  float64
 30  Shuman                      24887 non-null  float64
 31  ShumanRavuy                 10951 non-null  float64
 32  ShumanTrans                 9215 non-null   float64
 33  Colastrol                   9328 non-null   float64
 34  SivimTzunatim               7176 non-null   float64
 35  CafiotSucar                 3821 non-null   float64
 36  DepartmentCodeSubs          37912 non-null  int64
 37  CategoryCodeSubs            37912 non-null  int64
 38  GroupCodeSubs               37912 non-null  int64
 39  SubGroupCodeSubs            37912 non-null  int64
 40  CompoundIDSubs              37912 non-null  float64
 41  ProductNumberSubs           37912 non-null  float64
 42  BrandIndDescSuss            37910 non-null  object
 43  BrandNameSubs               37912 non-null  object
 44  VendorNumberSubs            37911 non-null  float64
 45  UnitOfMeasureSubs           37912 non-null  float64
 46  PriceSubs                   37912 non-null  float64
 47  NetSaleNoVatPrdSubs         37430 non-null  float64
 48  QuantSaleSubs               37492 non-null  float64
 49  cntMonthsSubs               37912 non-null  int64
 50  DiscountPerUnitSubs         324 non-null    float64
 51  EnergySubs                  33371 non-null  float64
 52  PachmemaSubs                27024 non-null  float64
 53  NatranSubs                  32271 non-null  float64
 54  HelbonSubs                  31769 non-null  float64
 55  ShumanSubs                  17109 non-null  float64
 56  ShumanRavuySubs             10480 non-null  float64
 57  ShumanTransSubs             10203 non-null  float64
 58  ColastrolSubs               12976 non-null  float64
 59  SivimTzunatimSubs           11965 non-null  float64
 60  CafiotSucarSusb             6654 non-null   float64
 61  CorrelateItemStatusCode     37912 non-null  int64
dtypes: float64(36), int64(19), object(7)
memory usage: 17.9+ MB

None

In [ ]:
# Fix Typo mistake
if RAW: 
  df2.rename(columns={'OrderNumbert': 'OrderNumber','BrandIndDescSuss': 'BrandIndDescSubs', 'ProductNumberSubs': 'ParentProductNumberSubs', 
                    'NetSaleNoVatPrdSubs': 'NetSaleNoVatPrdLast3MonthsSubs', 'CafiotSucarSusb': 'CafiotSucarSubs'}, inplace=True)

Eliminating nulls

In [ ]:
# Fill na
if RAW:
  df2.fillna({'QuantSale': 1, 'QuantSaleSubs': 1}, inplace=True)
  df2.fillna(0, inplace=True)
  d(df2.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 37912 entries, 0 to 37911
Data columns (total 62 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   HouseHoldID                     37912 non-null  int64
 1   LocationCityName                37912 non-null  object
 2   QuarterNumber                   37912 non-null  int64
 3   MonthNumber                     37912 non-null  int64
 4   WeekNumber                      37912 non-null  int64
 5   DayNumberInWeek                 37912 non-null  int64
 6   PeriodHoliday                   37912 non-null  object
 7   DepartmentCode                  37912 non-null  int64
 8   CategoryCode                    37912 non-null  int64
 9   GroupCode                       37912 non-null  int64
 10  SubGroupCode                    37912 non-null  int64
 11  CompoundID                      37912 non-null  float64
 12  ParentProductNumber             37912 non-null  float64
 13  BrandIndDesc                    37912 non-null  object
 14  BrandName                       37912 non-null  object
 15  VendorNumber                    37912 non-null  int64
 16  UnitOfMeasure                   37912 non-null  float64
 17  Price                           37912 non-null  float64
 18  Quantity                        37912 non-null  int64
 19  cntPrdAll                       37912 non-null  int64
 20  NetSaleAmountAll                37912 non-null  float64
 21  NetSaleNoVatPrdLast3Months      37912 non-null  float64
 22  QuantSale                       37912 non-null  float64
 23  cntMonths                       37912 non-null  int64
 24  DiscountPerUnit                 37912 non-null  float64
 25  isPromo                         37912 non-null  object
 26  Energy                          37912 non-null  float64
 27  Pachmema                        37912 non-null  float64
 28  Natran                          37912 non-null  float64
 29  Helbon                          37912 non-null  float64
 30  Shuman                          37912 non-null  float64
 31  ShumanRavuy                     37912 non-null  float64
 32  ShumanTrans                     37912 non-null  float64
 33  Colastrol                       37912 non-null  float64
 34  SivimTzunatim                   37912 non-null  float64
 35  CafiotSucar                     37912 non-null  float64
 36  DepartmentCodeSubs              37912 non-null  int64
 37  CategoryCodeSubs                37912 non-null  int64
 38  GroupCodeSubs                   37912 non-null  int64
 39  SubGroupCodeSubs                37912 non-null  int64
 40  CompoundIDSubs                  37912 non-null  float64
 41  ParentProductNumberSubs         37912 non-null  float64
 42  BrandIndDescSubs                37912 non-null  object
 43  BrandNameSubs                   37912 non-null  object
 44  VendorNumberSubs                37912 non-null  float64
 45  UnitOfMeasureSubs               37912 non-null  float64
 46  PriceSubs                       37912 non-null  float64
 47  NetSaleNoVatPrdLast3MonthsSubs  37912 non-null  float64
 48  QuantSaleSubs                   37912 non-null  float64
 49  cntMonthsSubs                   37912 non-null  int64
 50  DiscountPerUnitSubs             37912 non-null  float64
 51  EnergySubs                      37912 non-null  float64
 52  PachmemaSubs                    37912 non-null  float64
 53  NatranSubs                      37912 non-null  float64
 54  HelbonSubs                      37912 non-null  float64
 55  ShumanSubs                      37912 non-null  float64
 56  ShumanRavuySubs                 37912 non-null  float64
 57  ShumanTransSubs                 37912 non-null  float64
 58  ColastrolSubs                   37912 non-null  float64
 59  SivimTzunatimSubs               37912 non-null  float64
 60  CafiotSucarSubs                 37912 non-null  float64
 61  CorrelateItemStatusCode         37912 non-null  int64
dtypes: float64(36), int64(19), object(7)
memory usage: 17.9+ MB

None

In [ ]:
if RAW and False:
  df2.to_csv(prefix + ".csv", index = False)
  p(df2.shape)

(37912, 62)

In [ ]:
if RAW and False:
  df = pd.read_csv(prefix + '.csv', index_col=False)
else:
  df = df2.copy()
p(df.shape)

(37912, 62)

## Encoding categories

In [ ]:
from sklearn.preprocessing import LabelEncoder
enc = LabelEncoder()

if RAW:
  enc.fit(['PromoSusbDiffPromo', 'PromoSusbSamePromo', 'noPromo'])
  p(df.isPromo.value_counts())
  p()
  df.isPromo = enc.transform(df.isPromo)
  p(df.isPromo.value_counts())

noPromo               19746
PromoSusbDiffPromo    18059
PromoSusbSamePromo      107
Name: isPromo, dtype: int64

2    19746
0    18059
1      107
Name: isPromo, dtype: int64

In [ ]:
if RAW:
  for col in ['LocationCityName', 'PeriodHoliday', 'BrandIndDesc', 'BrandName', 'BrandIndDescSubs', 'BrandNameSubs']:
    p(col)
    p(pd.DataFrame(df[col].value_counts()).index)
    df[col] = enc.fit_transform(df[col])
    p(pd.DataFrame(df[col].value_counts()).index)

LocationCityName
Index(['ראשון לציון', 'תל אביב', 'רחובות', 'כפר סבא', 'חיפה', 'רעננה',
       'פתח תקוה', 'ירושלים', 'נס ציונה', 'ראש העין', 'רמת גן', 'נתניה',
       'חולון', 'רמת השרון', 'אילת', 'יהוד', 'אשקלון', 'מודיעין', 'גבעתיים',
       'הוד השרון', 'באר יעקב', 'עפולה', 'קרית מוצקין', 'שוהם', 'הרצליה',
       'כרמיאל', 'חדרה', 'רמת אביב א', 'חריש', 'זכרון יעקב', 'טירת הכרמל',
       'קרית שמונה', 'בת ים', 'מזכרת בתיה', 'בנימינה', 'קרית ביאליק', 'יבנה',
       'צור-יגאל', 'עמק חפר', 'קצרין', 'ערד', 'בני ברק', 'פרדסיה',
       'משמר השרון', 'ירוחם', 'תל מונד', 'קרית אתא', 'פרדס חנה', 'קרית עקרון',
       'רמלה', 'אשדוד', 'מגדל העמק', 'נהריה', 'בית שאן', 'מעלה אדומים',
       'חצור-הגלילית', 'אור עקיבא', 'גבעת עדה', 'באר טוביה', 'כפר תבור',
       'גבעת אולגה', 'שדרות', 'כרכור', 'קרית גת', 'בת חפר', 'מפרץ חיפה',
       'באר שבע', 'גבעת שמואל', 'בית-שמש', 'צור משה', 'אריאל', 'נשר', 'גדרה',
       'קרית חיים', 'מבשרת ציון', 'אופקים', 'טבריה', 'צפת', 'צורן קדימה', '0',
       'שילת', 'נוף הגליל', 'בית חשמונאי', 'כפר ורדים', 'מעלות', 'אזור',
       'סביון', 'מיתר', 'צומת כרכור', 'כפר נטר', 'יקנעם', 'טבעון', 'קרית אונו',
       'צור הדסה', 'ראש פינה', 'בני דרור', 'דימונה', 'עכו', 'קריית שמונה'],
      dtype='object')
Int64Index([87, 97, 88, 43, 30, 93, 68, 40, 58, 85, 91, 60, 29, 92,  4, 37,  7,
            49, 22, 25,  9, 64, 82, 95, 26, 46, 28, 90, 32, 84, 27, 35, 18, 50,
            16, 79, 36, 72, 63, 75, 65, 14, 67, 39, 55, 98, 78, 66, 83, 89, 48,
             6, 56, 12, 52,  2, 31, 20,  8, 44, 19, 94, 45, 17, 80, 10, 54, 21,
            13, 59, 71,  5, 23,  1, 47, 81, 34, 74, 73,  0, 96, 41, 11, 57, 61,
             3, 53, 69, 42, 51, 38, 86, 33, 77, 70, 24, 15, 76, 62],
           dtype='int64')
PeriodHoliday
Index(['NotHoliday', 'HolidayPeriod'], dtype='object')
Int64Index([1, 0], dtype='int64')
BrandIndDesc
Index(['MUTTI', 'סטארקיסט', 'שופרסל', 'וילי פוד', 'יכין', 'בית השיטה',
       'פרי ניר', 'פיל טונה', 'זיתא', 'קבוצת יבנה', 'תומר', 'פומי',
       'פרי הגליל', 'ריו מארה', 'פומו', 'בלה איטליה', 'טעם הטבע', 'לינה',
       'עץ הזית', 'דלידג', 'ויליגר', 'מאסטר שף', 'מוטולה', 'סרה', 'קלית גת',
       'רוברט', 'אורבנק', 'פורטוס', 'פוסידון', 'אידיאל', 'היינץ',
       'ARNOLD SOREN', 'פרי חן', 'נון', 'פרינס טונה', 'קינג קול', 'גאלה',
       'קפרימאר', 'נפטון', 'סניידרס', 'ריגה', 'טקסן', 'רויאל ריגה', 'דל מונטה',
       'סאקלה', '0', 'רוגן פיש'],
      dtype='object')
Int64Index([ 2, 23, 45, 11, 16,  5, 34, 31, 13, 36, 46, 28, 32, 44, 27,  6, 14,
            17, 26,  9, 12, 18, 19, 25, 38, 40,  3, 30, 29,  4, 10, 33,  1, 20,
            35, 37,  7, 24, 21, 39, 43, 42, 15,  8, 22, 41,  0],
           dtype='int64')
BrandName
Index(['לא מותג פרטי', 'מותג פרטי'], dtype='object')
Int64Index([0, 1], dtype='int64')
BrandIndDescSubs
Index(['שופרסל', 'סטארקיסט', 'פרי ניר', 'יכין', 'בית השיטה', 'MUTTI',
       'פיל טונה', 'קבוצת יבנה', 'בלה איטליה', 'זיתא', 'וילי פוד', 'לינה',
       'תומר', 'מאסטר שף', 'פומו', 'פומי', 'דל מונטה', 'ריו מארה', 'פרי הגליל',
       'עץ הזית', 'טעם הטבע', 'ויליגר', 'רוברט', 'אידיאל', 'פורטוס', 'סרה',
       'שופרסל גרין', 'אורבנק', 'מוטולה', 'קלית גת', 'נפטון', 'פרינס טונה',
       'ARNOLD SOREN', 'השוק הקולינר', 'גאלה', 'ליב', 'סניידרס', 'פרי חן',
       'יד מרדכי', 'פרפקטו', 'ריגה', 'פוסידון', 'היינץ', 'רויאל ריגה',
       'פרינוק', 'שקדיה', 'קינג קול', 'סוגת', 'קפרימאר', 'גרבר', '0',
       'אירו מחלבות', 'בלו אלפנט', 'סאקלה', 'פרה', 'צבר', 'בון מאמא', 'דול',
       'נון', 'טקסן', 'ברילה', 'פריגת', 'אסם', 'עללחם', 'דלידג'],
      dtype='object')
Int64Index([61, 34, 47, 25,  8,  2, 43, 53,  9, 21, 19, 27, 64, 28, 39, 40, 15,
            60, 45, 38, 22, 20, 57,  4, 42, 36, 62,  3, 29, 55, 31, 50,  1, 18,
            12, 26, 46, 35, 24, 51, 59, 17, 41, 63, 49, 58, 54, 33, 56,  0, 13,
            32, 30, 23, 52, 10, 11,  5, 37,  6, 16,  7, 14, 44, 48],
           dtype='int64')
BrandNameSubs
Index(['לא מותג פרטי', 'מותג פרטי'], dtype='object')
Int64Index([0, 1], dtype='int64')

## Combine 'GroupCode' and 'SubGroupCode' into one column

In [ ]:
if RAW:
  d(df.head(2))
  df.SubGroupCode = df.GroupCode * 10 + df.SubGroupCode
  df.SubGroupCodeSubs = df.GroupCodeSubs * 10 + df.SubGroupCodeSubs
#  df.drop(['SubGroupCode', 'SubGroupCodeSubs'], axis=1, inplace=True)
  d(df.head(2))

   HouseHoldID  LocationCityName  ...  CafiotSucarSubs  CorrelateItemStatusCode
0            1                97  ...             0.75                        1
1            2                87  ...             2.50                        1

[2 rows x 62 columns]

   HouseHoldID  LocationCityName  ...  CafiotSucarSubs  CorrelateItemStatusCode
0            1                97  ...             0.75                        1
1            2                87  ...             2.50                        1

[2 rows x 62 columns]

## Use Dummies

Minimal improvement - FalseNegative (0,0) improved from 1338 to 1328

In [ ]:
## Converting the categories column (isPromo) to dummies column 
if RAW:
  p(df.shape)
  df = pd.get_dummies(df, columns=['isPromo', 'PeriodHoliday'])
  p(df.shape)

(37912, 62)
(37912, 65)

In [ ]:
if RAW:
  df_t = df.copy()

## Calc diff vector

In [ ]:
if RAW:
  p(df.columns)

Index(['HouseHoldID', 'LocationCityName', 'QuarterNumber', 'MonthNumber',
       'WeekNumber', 'DayNumberInWeek', 'DepartmentCode', 'CategoryCode',
       'GroupCode', 'SubGroupCode', 'CompoundID', 'ParentProductNumber',
       'BrandIndDesc', 'BrandName', 'VendorNumber', 'UnitOfMeasure', 'Price',
       'Quantity', 'cntPrdAll', 'NetSaleAmountAll',
       'NetSaleNoVatPrdLast3Months', 'QuantSale', 'cntMonths',
       'DiscountPerUnit', 'Energy', 'Pachmema', 'Natran', 'Helbon', 'Shuman',
       'ShumanRavuy', 'ShumanTrans', 'Colastrol', 'SivimTzunatim',
       'CafiotSucar', 'DepartmentCodeSubs', 'CategoryCodeSubs',
       'GroupCodeSubs', 'SubGroupCodeSubs', 'CompoundIDSubs',
       'ParentProductNumberSubs', 'BrandIndDescSubs', 'BrandNameSubs',
       'VendorNumberSubs', 'UnitOfMeasureSubs', 'PriceSubs',
       'NetSaleNoVatPrdLast3MonthsSubs', 'QuantSaleSubs', 'cntMonthsSubs',
       'DiscountPerUnitSubs', 'EnergySubs', 'PachmemaSubs', 'NatranSubs',
       'HelbonSubs', 'ShumanSubs', 'ShumanRavuySubs', 'ShumanTransSubs',
       'ColastrolSubs', 'SivimTzunatimSubs', 'CafiotSucarSubs',
       'CorrelateItemStatusCode', 'isPromo_0', 'isPromo_1', 'isPromo_2',
       'PeriodHoliday_0', 'PeriodHoliday_1'],
      dtype='object')

In [ ]:
if RAW and DIFF:
  for col in ['DepartmentCode', 'CategoryCode', 'GroupCode', #'SubGroupCode',
       'CompoundID', 'ParentProductNumber', 'BrandIndDesc',
       'VendorNumber', 'UnitOfMeasure', 'Price', 'NetSaleNoVatPrdLast3Months', 'Energy', 'Pachmema',
       'Natran', 'Helbon', 'Shuman', 'ShumanRavuy', 'ShumanTrans', 'Colastrol',
       'SivimTzunatim', 'CafiotSucar', 'QuantSale', 'cntMonths', 'DiscountPerUnit']:
    df[col + 'Diff'] = df[col] - df[col + 'Subs']

In [ ]:
if RAW and DIFF:
  for col in ['DepartmentCode', 'CategoryCode', 'GroupCode', #'SubGroupCode',
       'CompoundID', 'ParentProductNumber', 'VendorNumber', 'BrandIndDesc']:
    df[col + 'Diff'] = (df[col + 'Diff'] != 0)    # tested both ==0 and !=0 (the result is 1 for one and 0 for the other - no change in the model results)
    df[col + 'Diff'] = enc.fit_transform(df[col + 'Diff'])

In [ ]:
if RAW and DIFF:
  df.to_csv(prefix + "_with_diff.csv", index = False)

In [ ]:
if RAW and DIFF:
  df = pd.read_csv(prefix + '_with_diff.csv', index_col=False)
  p(df.shape)

(37912, 88)

# Get ready Data

In [ ]:
if RAW:
  p(df.shape)
  d(df.head())

(37912, 88)

   HouseHoldID  LocationCityName  ...  cntMonthsDiff  DiscountPerUnitDiff
0            1                97  ...              8                6.890
1            2                87  ...              0                0.000
2            3                87  ...             14                6.895
3            4                30  ...              0                6.896
4            5                87  ...              8                6.875

[5 rows x 88 columns]

In [ ]:
if not RAW:
  df = pd.read_csv(prefix + '_with_diff.csv', encoding='ISO-8859-8')
  p(df.shape)
  d(df.head())

(37912, 88)

   HouseHoldID  LocationCityName  ...  cntMonthsDiff  DiscountPerUnitDiff
0            1                97  ...              8                6.890
1            2                87  ...              0                0.000
2            3                87  ...             14                6.895
3            4                30  ...              0                6.896
4            5                87  ...              8                6.875

[5 rows x 88 columns]

# Models

In [ ]:
REMOVE_ING = False
SPLIT_DATE = False
ONLY_PRICE = False
GS = False
CV = False

## Models - remove ingredients - no change in results

In [ ]:
if REMOVE_ING:
  id = 'remove ingredients'
  try:
    del X_train, X_test, y_train, y_test
  except:
    pass
  
  cols = ['CorrelateItemStatusCode']
  for col in ['Energy', 'Pachmema', 'Natran', 'Helbon', 'Shuman', 'ShumanRavuy', 'ShumanTrans', 'Colastrol',
       'SivimTzunatim', 'CafiotSucar']:
      cols.append(col)
      cols.append(col + 'Subs')
      cols.append(col + 'Diff')

  X = df.drop(cols, axis=1)
  y = df.CorrelateItemStatusCode.astype(int)

  X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.7, random_state=0)
  p(df.shape)
  p(X_train.shape, X_test.shape, y_train.shape, y_test.shape)

(37912, 88)

(26538, 57) (11374, 57) (26538,) (11374,)

## Models - remove all features execpt of prices

In [ ]:
if ONLY_PRICE:
  id = 'only_prices'
  try:
    del X_train, X_test, y_train, y_test
  except:
    pass
  
  X = df[['Price', 'PriceSubs', 'PriceDiff']]
  y = df.CorrelateItemStatusCode.astype(int)

  X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.7, random_state=0)
  p(df.shape)
  p(X_train.shape, X_test.shape, y_train.shape, y_test.shape)

(37912, 88)

(26538, 3) (11374, 3) (26538,) (11374,)

## Models - Train on sweets, test on cans

In [ ]:
if SWEETS:
  get_raw('Shufersal_with_diff.csv')
  df = pd.read_csv('Shufersal_with_diff.csv', index_col=False)
  p(df.shape)
  d(df.head(1))

In [ ]:
if SWEETS:
  df_sweets = pd.read_csv('Shufersal_with_diff.csv', index_col=False)
  X_train = df_sweets.drop('CorrelateItemStatusCode', axis=1)
  y_train = df_sweets.CorrelateItemStatusCode.astype(int)

  p(df_sweets.shape, X_train.shape, y_train.shape)
  d(df_sweets.head())

In [ ]:
if SWEETS:
  df_cans = pd.read_csv(prefix + '_with_diff.csv', index_col=False)
  X_test = df_cans.drop('CorrelateItemStatusCode', axis=1)
  y_test = df_cans.CorrelateItemStatusCode.astype(int)

  p(df_cans.shape, X_test.shape, y_test.shape)
  d(df_cans.head())

  id = 'train_sweet_pred_cans'


## Models - process_model code

In [ ]:
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score
import math

pd.set_option("precision", 2)
df_result = pd.DataFrame()

In [ ]:
from sklearn.model_selection import train_test_split, GridSearchCV, cross_val_score

X = df.drop('CorrelateItemStatusCode', axis=1)
y = df.CorrelateItemStatusCode.astype(int)

X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.7, random_state=0)

In [ ]:
def report(clf, X, y, note, test, data_type='Test'):
  global df_result
  name = type(clf).__name__ + ': ' + data_type
  acc = accuracy_score(y_true=y, y_pred=clf.predict(X))
  index = [(name, clf.classes_[0]), (name, clf.classes_[1])]
  cm = pd.DataFrame(confusion_matrix(y_true=y, y_pred=clf.predict(X)),
                    index=clf.classes_,
                    columns=clf.classes_)
  cm.reset_index(drop=True, inplace=True)
  rep = classification_report(y_true=y, y_pred=clf.predict(X), zero_division=1, output_dict=True)
  rep =  pd.DataFrame(rep)
  rep = rep.T
  rep['accuracy'] = acc
  rep.support = rep.support.astype(int)
  cols = list(rep.columns[:3]) + ['accuracy', 'support']
  rep = rep[cols]
  rep['precision_avg'] = rep.precision['macro avg']
  rep['recall_avg'] = rep.recall['macro avg']
  rep['f1-score_avg'] = rep['f1-score']['macro avg']
  rep.drop(['accuracy', 'macro avg', 'weighted avg'], axis=0, inplace=True)
  rep.reset_index(drop=True, inplace=True)
  df = cm.join(rep)
  df['name'] = name
  df['note'] = note
  df.loc[1, 'note'] = ''
  if test:  # do not add to database
    d(df)
  else:    
    df.reset_index(inplace=True)
    df_result.reset_index(inplace=True)
    df_result = df_result.append(df, ignore_index=True)
    df_result.set_index(['name', 'index'], inplace=True)
  return df_result

In [ ]:
#ROC and AUC
from sklearn.metrics import roc_curve
from sklearn.metrics import roc_auc_score

def get_roc_and_auc(model,X_test,y_test):
    ns_probs = [0 for _ in range(len(y_test))]
#    lr_probs = clf_voting.predict_proba(X_test)[:,1]
    lr_probs = model.predict_proba(X_test)[:,1]
    ns_auc = roc_auc_score(y_test, ns_probs)
    lr_auc = roc_auc_score(y_test, lr_probs)
    # summarize scores
    print('\nNo Skill: ROC AUC=%.3f' % (ns_auc))
    print('model: ROC AUC=%.3f' % (lr_auc))
    # calculate roc curves
    ns_fpr, ns_tpr, _ = roc_curve(y_test, ns_probs)
    lr_fpr, lr_tpr, _ = roc_curve(y_test, lr_probs)
    # plot the roc curve for the model
    fig = plt.figure(figsize=(5,5))
    plt.plot(ns_fpr, ns_tpr, linestyle='--', label='No Skill')
    plt.plot(lr_fpr, lr_tpr, marker='.', label='model')
    # axis labels
    plt.xlabel('False Positive Rate')
    plt.ylabel('True Positive Rate')
    plt.title(type(model).__name__ )
    # show the legend
    plt.legend()
    # show the plot
    plt.show()

In [ ]:
def showFeatureImportance(model, X, threshold):
  if type(model).__name__ == 'LogisticRegression':  # no features importance data
    w0 = model.intercept_[0]
    w = model.coef_[0]
    fx_imp = pd.Series(w, index=X.columns)
  else:
    fx_imp = pd.Series(model.feature_importances_, index=X.columns)
  fx_imp /= fx_imp.sum()
  fx_imp = fx_imp.sort_values()
  fx_imp = fx_imp[fx_imp > threshold]
  fig = plt.figure(figsize=(5,5))
  plt.xlim(0, 1)
  fx_imp.plot(kind='barh', title=type(model).__name__ )

In [ ]:
def process_model(model, X, y, X_test, y_test, plot=False, threshold=0, note='', test=False):
  p('running: ', type(model).__name__, X.shape)
  model.fit(X, y)
  report(model, X, y, note, test, 'Train')
  report(model, X_test, y_test, note, test)
  if plot:
    showFeatureImportance(model, X, threshold)
    get_roc_and_auc(model,X_test,y_test)    
  return df_result

In [ ]:
from sklearn.linear_model import LogisticRegression, BayesianRidge, Lasso, Ridge
from sklearn.ensemble import GradientBoostingClassifier, RandomForestClassifier, AdaBoostClassifier, GradientBoostingRegressor, BaggingClassifier, VotingClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import LinearSVC


## Models - Run process_model

In [ ]:
df_result = pd.DataFrame()

clf_RF = RandomForestClassifier(n_estimators=200, criterion='entropy', max_depth=None, min_samples_split=20, ccp_alpha=0.0003, random_state=73)
process_model(clf_RF, X_train, y_train, X_test, y_test, plot=False, threshold=0.015, note="n_estimators=200, criterion='entropy', max_depth=None, min_samples_split=20, ccp_alpha=0.0003, random_state=73")


d(df_result)

fname = prefix + f'_result_{id}.csv'
df_result.to_csv(fname, index = True)

running:  RandomForestClassifier (26538, 87)
running:  RandomForestClassifier (26538, 87)

                                          0        1  precision  recall  \
name                          index
RandomForestClassifier: Train 0      8245.0   2395.0       0.89    0.77
                              1       990.0  14908.0       0.86    0.94
RandomForestClassifier: Test  0      3329.0   1237.0       0.86    0.73
                              1       550.0   6258.0       0.83    0.92
RandomForestClassifier: Train 0      8211.0   2429.0       0.89    0.77
                              1       967.0  14931.0       0.86    0.94
RandomForestClassifier: Test  0      3335.0   1231.0       0.86    0.73
                              1       547.0   6261.0       0.84    0.92

                                     f1-score  accuracy  support  \
name                          index
RandomForestClassifier: Train 0          0.83      0.87  10640.0
                              1          0.90      0.87  15898.0
RandomForestClassifier: Test  0          0.79      0.84   4566.0
                              1          0.88      0.84   6808.0
RandomForestClassifier: Train 0          0.83      0.87  10640.0
                              1          0.90      0.87  15898.0
RandomForestClassifier: Test  0          0.79      0.84   4566.0
                              1          0.88      0.84   6808.0

                                     precision_avg  recall_avg  f1-score_avg  \
name                          index
RandomForestClassifier: Train 0               0.88        0.86          0.86
                              1               0.88        0.86          0.86
RandomForestClassifier: Test  0               0.85        0.82          0.83
                              1               0.85        0.82          0.83
RandomForestClassifier: Train 0               0.88        0.86          0.86
                              1               0.88        0.86          0.86
RandomForestClassifier: Test  0               0.85        0.83          0.83
                              1               0.85        0.83          0.83

                                                                                  note
name                          index
RandomForestClassifier: Train 0      n_estimators=200, criterion='entropy', max_dep...
                              1
RandomForestClassifier: Test  0      n_estimators=200, criterion='entropy', max_dep...
                              1
RandomForestClassifier: Train 0      n_estimators=200, criterion='entropy', max_dep...
                              1
RandomForestClassifier: Test  0      n_estimators=200, criterion='entropy', max_dep...
                              1

## Models - compare results

1. Diff
2. Diff with remove ingredients columns
6. OnlyPrices - Diff with only 3 features( Price, PriceSubs, PriceDiff)
7. Train on sweets, predict on cans
8. No Diff (no comparison between master and subs)

In [ ]:
def read_results(id='', disp=True, full=False):
  fname = prefix + f'_result_{id}.csv'
  p(fname)
  try:
    df = pd.read_csv(fname)
  except:
    try:
      get_raw(fname, 'Results/')
      df = pd.read_csv(fname)
    except:
      p('No data')
      return
  df.set_index(['name', 'index'], inplace=True)
  if not full:
    df = df.loc[['RandomForestClassifier: Train', 'RandomForestClassifier: Test']]#.copy()
  if disp:
    pd.set_option("max_column", 120)
    d(df)
  return df

In [ ]:
p(id)
read_results()
read_results('remove ingredients')
read_results('only_prices')
read_results('train_sweet_pred_cans')
read_results('no diff')
p()

Shufersal_cans_result_.csv

                                          0        1  precision  recall  \
name                          index
RandomForestClassifier: Train 0      8245.0   2395.0       0.89    0.77
                              1       990.0  14908.0       0.86    0.94
RandomForestClassifier: Test  0      3329.0   1237.0       0.86    0.73
                              1       550.0   6258.0       0.83    0.92

                                     f1-score  accuracy  support  \
name                          index
RandomForestClassifier: Train 0          0.83      0.87  10640.0
                              1          0.90      0.87  15898.0
RandomForestClassifier: Test  0          0.79      0.84   4566.0
                              1          0.88      0.84   6808.0

                                     precision_avg  recall_avg  f1-score_avg  \
name                          index
RandomForestClassifier: Train 0               0.88        0.86          0.86
                              1               0.88        0.86          0.86
RandomForestClassifier: Test  0               0.85        0.82          0.83
                              1               0.85        0.82          0.83

                                                                                  note
name                          index
RandomForestClassifier: Train 0      n_estimators=200, criterion='entropy', max_dep...
                              1                                                    NaN
RandomForestClassifier: Test  0      n_estimators=200, criterion='entropy', max_dep...
                              1                                                    NaN

Shufersal_cans_result_remove ingredients.csv

                                          0        1  precision  recall  \
name                          index
RandomForestClassifier: Train 0      8238.0   2402.0       0.90    0.77
                              1       926.0  14972.0       0.86    0.94
RandomForestClassifier: Test  0      3321.0   1245.0       0.86    0.73
                              1       524.0   6284.0       0.83    0.92

                                     f1-score  accuracy  support  \
name                          index
RandomForestClassifier: Train 0          0.83      0.87  10640.0
                              1          0.90      0.87  15898.0
RandomForestClassifier: Test  0          0.79      0.84   4566.0
                              1          0.88      0.84   6808.0

                                     precision_avg  recall_avg  f1-score_avg  \
name                          index
RandomForestClassifier: Train 0               0.88        0.86          0.87
                              1               0.88        0.86          0.87
RandomForestClassifier: Test  0               0.85        0.83          0.83
                              1               0.85        0.83          0.83

                                                                                  note
name                          index
RandomForestClassifier: Train 0      n_estimators=200, criterion='entropy', max_dep...
                              1                                                    NaN
RandomForestClassifier: Test  0      n_estimators=200, criterion='entropy', max_dep...
                              1                                                    NaN

Shufersal_cans_result_only_prices.csv

                                          0        1  precision  recall  \
name                          index
RandomForestClassifier: Train 0      7782.0   2858.0       0.79    0.73
                              1      2060.0  13838.0       0.83    0.87
RandomForestClassifier: Test  0      3260.0   1306.0       0.78    0.71
                              1       938.0   5870.0       0.82    0.86

                                     f1-score  accuracy  support  \
name                          index
RandomForestClassifier: Train 0          0.76      0.81  10640.0
                              1          0.85      0.81  15898.0
RandomForestClassifier: Test  0          0.74      0.80   4566.0
                              1          0.84      0.80   6808.0

                                     precision_avg  recall_avg  f1-score_avg  \
name                          index
RandomForestClassifier: Train 0               0.81        0.80          0.80
                              1               0.81        0.80          0.80
RandomForestClassifier: Test  0               0.80        0.79          0.79
                              1               0.80        0.79          0.79

                                                                                  note
name                          index
RandomForestClassifier: Train 0      n_estimators=200, criterion='entropy', max_dep...
                              1                                                    NaN
RandomForestClassifier: Test  0      n_estimators=200, criterion='entropy', max_dep...
                              1                                                    NaN

Shufersal_cans_result_train_sweet_pred_cans.csv

                                           0        1  precision  recall  \
name                          index
RandomForestClassifier: Train 0      12719.0   5349.0       0.84    0.70
                              1       2412.0  33980.0       0.86    0.93
RandomForestClassifier: Test  0       9813.0   5393.0       0.67    0.65
                              1       4873.0  17833.0       0.77    0.79

                                     f1-score  accuracy  support  \
name                          index
RandomForestClassifier: Train 0          0.77      0.86  18068.0
                              1          0.90      0.86  36392.0
RandomForestClassifier: Test  0          0.66      0.73  15206.0
                              1          0.78      0.73  22706.0

                                     precision_avg  recall_avg  f1-score_avg  \
name                          index
RandomForestClassifier: Train 0               0.85        0.82          0.83
                              1               0.85        0.82          0.83
RandomForestClassifier: Test  0               0.72        0.72          0.72
                              1               0.72        0.72          0.72

                                                                                  note
name                          index
RandomForestClassifier: Train 0      n_estimators=200, criterion='entropy', max_dep...
                              1                                                    NaN
RandomForestClassifier: Test  0      n_estimators=200, criterion='entropy', max_dep...
                              1                                                    NaN